
import React from "react";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const PrivacyPolicyPage = () => {
  return (
    <div className="flex flex-col min-h-screen">
      <Header />
      <main className="flex-1 container mx-auto py-8 px-4 max-w-4xl">
        <h1 className="text-3xl font-bold mb-6">Privacy Policy</h1>
        <p className="text-muted-foreground mb-6">Last updated: April 1, 2023</p>

        <div className="prose max-w-none">
          <p className="mb-4">
            At AgentCreator, we take your privacy seriously. This Privacy Policy explains how we collect, use, 
            disclose, and safeguard your information when you use our website and services.
          </p>

          <h2 className="text-2xl font-semibold mt-8 mb-4">Information We Collect</h2>
          
          <h3 className="text-xl font-medium mt-6 mb-3">Personal Information</h3>
          <p className="mb-4">
            We may collect personal information that you voluntarily provide to us when you:
          </p>
          <ul className="list-disc pl-6 mb-4 space-y-2">
            <li>Create an account</li>
            <li>Use our services</li>
            <li>Contact our customer support</li>
            <li>Participate in surveys or promotions</li>
            <li>Subscribe to our newsletter</li>
          </ul>
          <p className="mb-4">
            This information may include your name, email address, company name, job title, billing information, 
            and any other information you choose to provide.
          </p>

          <h3 className="text-xl font-medium mt-6 mb-3">Usage Information</h3>
          <p className="mb-4">
            We automatically collect certain information when you visit, use, or navigate our website and services. 
            This information may include:
          </p>
          <ul className="list-disc pl-6 mb-4 space-y-2">
            <li>Device and browser information</li>
            <li>IP address</li>
            <li>Usage patterns and preferences</li>
            <li>Referring URLs</li>
            <li>Click data</li>
          </ul>

          <h3 className="text-xl font-medium mt-6 mb-3">Data Used for AI Models</h3>
          <p className="mb-4">
            When you use our AI agent creation services, we may collect and process the data you provide to train 
            and optimize your AI agents. This may include:
          </p>
          <ul className="list-disc pl-6 mb-4 space-y-2">
            <li>Training data you upload</li>
            <li>User interactions with your AI agents</li>
            <li>Content generated by your AI agents</li>
          </ul>

          <h2 className="text-2xl font-semibold mt-8 mb-4">How We Use Your Information</h2>
          <p className="mb-4">
            We use the information we collect for various purposes, including:
          </p>
          <ul className="list-disc pl-6 mb-4 space-y-2">
            <li>Providing and improving our services</li>
            <li>Processing transactions and managing your account</li>
            <li>Responding to your inquiries and providing customer support</li>
            <li>Sending administrative information and marketing communications</li>
            <li>Training and optimizing AI models</li>
            <li>Analyzing usage patterns to improve our services</li>
            <li>Ensuring security and preventing fraud</li>
            <li>Complying with legal obligations</li>
          </ul>

          <h2 className="text-2xl font-semibold mt-8 mb-4">How We Share Your Information</h2>
          <p className="mb-4">
            We may share your information with:
          </p>
          <ul className="list-disc pl-6 mb-4 space-y-2">
            <li><strong>Service Providers:</strong> Third-party vendors who help us provide and improve our services</li>
            <li><strong>Business Partners:</strong> Companies we collaborate with to offer integrated or co-branded services</li>
            <li><strong>Legal Authorities:</strong> When required by law or to protect our rights</li>
            <li><strong>Business Transfers:</strong> In connection with a merger, acquisition, or sale of assets</li>
          </ul>
          <p className="mb-4">
            We will not sell your personal information to third parties.
          </p>

          <h2 className="text-2xl font-semibold mt-8 mb-4">Data Security</h2>
          <p className="mb-4">
            We implement appropriate technical and organizational measures to protect your personal information. 
            However, no method of transmission over the Internet or electronic storage is 100% secure. While we 
            strive to use commercially acceptable means to protect your personal information, we cannot guarantee its absolute security.
          </p>

          <h2 className="text-2xl font-semibold mt-8 mb-4">Your Privacy Rights</h2>
          <p className="mb-4">
            Depending on your location, you may have certain rights regarding your personal information, including:
          </p>
          <ul className="list-disc pl-6 mb-4 space-y-2">
            <li>Right to access and receive a copy of your personal information</li>
            <li>Right to rectify or update your personal information</li>
            <li>Right to erasure (right to be forgotten)</li>
            <li>Right to restrict processing</li>
            <li>Right to data portability</li>
            <li>Right to object to processing</li>
            <li>Right to withdraw consent</li>
          </ul>
          <p className="mb-4">
            To exercise these rights, please contact us at privacy@agentcreator.com.
          </p>

          <h2 className="text-2xl font-semibold mt-8 mb-4">Cookies and Similar Technologies</h2>
          <p className="mb-4">
            We use cookies and similar tracking technologies to collect and store information about your interactions 
            with our website and services. You can set your browser to refuse all or some browser cookies, but this 
            may limit your ability to use certain features of our website.
          </p>

          <h2 className="text-2xl font-semibold mt-8 mb-4">Children's Privacy</h2>
          <p className="mb-4">
            Our services are not intended for individuals under the age of 16. We do not knowingly collect personal 
            information from children. If you become aware that a child has provided us with personal information 
            without parental consent, please contact us at privacy@agentcreator.com.
          </p>

          <h2 className="text-2xl font-semibold mt-8 mb-4">Changes to This Privacy Policy</h2>
          <p className="mb-4">
            We may update this Privacy Policy from time to time. We will notify you of any changes by posting the 
            new Privacy Policy on this page and updating the "Last updated" date. You are advised to review this 
            Privacy Policy periodically for any changes.
          </p>

          <h2 className="text-2xl font-semibold mt-8 mb-4">Contact Us</h2>
          <p className="mb-4">
            If you have any questions about this Privacy Policy, please contact us at:
          </p>
          <p className="mb-4">
            Email: privacy@agentcreator.com<br />
            Address: 123 AI Avenue, San Francisco, CA 94107
          </p>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default PrivacyPolicyPage;
